Carify print code

diff --git a/shplug b/shplug
--- a/shplug
+++ b/shplug
@@ -20,6 +20,26 @@ have() {
     command -v "$1" >/dev/null
 }
 
+cursor() {
+    case "$1" in
+        up)
+            printf "\\033[%sA" "$2" ;;
+        down)
+            printf "\\033[%sB" "$2" ;;
+        home)
+            printf "\\r" ;;
+        clear)
+            mode=2
+            case "$2" in
+                end) mode=0 ;;
+                start) mode=1 ;;
+                line) mode=2 ;;
+            esac
+
+            printf "\\033[%sK" "$mode";;
+    esac
+}
+
 spinner() {
     frames='\|/-'
     while sleep 0.15; do
@@ -36,17 +56,19 @@ spinner() {
 }
 
 clone() {
-    sleep "$(echo "scale=9; $RANDOM*10/32767"|bc)" &
-    spinner "Cloning" $!
-
-    sleep "$(echo "scale=9; $RANDOM*10/32767"|bc)" &
-    spinner "Simulated process..." $!
-
-    echo "~ Simulated finish..."
-    # cd "$SHPLUG_SRC" && git clone "$1" 2>&1
+    cd "$SHPLUG_SRC" && git clone "$1" 1>&2 &
+    if spinner "Cloning $1" $!; then
+        echo "Done clone!"
+        return 0
+    else
+        echo "Failed clone!"
+        return 1
+    fi
 }
 
 register() {
+    mkdir -p "$SHPLUG_DIR"
+
     if ! [ -n "$1" ]; then
         err "missing git repository path!"
         exit 1
@@ -63,11 +85,15 @@ register() {
 
 load() {
     rm -rf "$SHPLUG_DIR/tmp/"
-    touch "$SHPLUG_DIR/queue"
     mkdir -p "$SHPLUG_SRC"
     mkdir -p "$SHPLUG_DIR/tmp/"
 
-    max_id=$(wc -l "$SHPLUG_DIR/queue" | cut -d' ' -f1)
+    queuefile="$SHPLUG_DIR/queue"
+    logfile="$SHPLUG_DIR/log"
+    touch "$queuefile"
+    touch "$logfile"
+
+    max_id=$(wc -l "$queuefile" | cut -d' ' -f1)
 
     for ii in $(seq 1 "$max_id"); do
         # eval "stat_$ii=PLACEHOLDER_$ii"
@@ -80,8 +106,14 @@ load() {
         i=0
         while read -r entry; do
             i=$((i+1))
-            clone "$(echo "$entry" | cut -f1)" | sed -u "s/^/$i	/" &
-        done < "$SHPLUG_DIR/queue"
+            clone "$(echo "$entry" | cut -f1)" | sed -u "s/^/$i	/" 2>"$logfile" &
+            pid=$!
+            # {
+            #     if wait $pid; then
+            #         eval "exit_code_$i=0"
+            #     fi
+            # } &
+        done < "$queuefile"
     } | {
         while read -r status; do
             id=$(echo "$status" | cut -d '	' -f1)
@@ -92,7 +124,13 @@ load() {
 
             lines_up=$((max_id + 1 - id))
 
-            printf "\\033[%dA\\r\\033[0K%s\\r\\033[%dB" $lines_up "$cur_stat" $lines_up
+            printf "%s" "$(
+                cursor up $lines_up
+                printf "%s" "$cur_stat"
+                cursor clear end
+                cursor home
+                cursor down $lines_up
+            )"
         done
     }
 
